version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: claude-context-postgres
    environment:
      POSTGRES_DB: embeddings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: claude-context-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: serve
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/api/tags || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Optional: MCP server container
  # Uncomment to run the MCP server in Docker
  # mcp-server:
  #   build: .
  #   container_name: claude-context-mcp
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     ollama:
  #       condition: service_healthy
  #   environment:
  #     EMBEDDING_PROVIDER: Ollama
  #     OLLAMA_MODEL: DC1LEX/nomic-embed-text-v1.5-multimodal
  #     OLLAMA_HOST: http://ollama:11434
  #     POSTGRES_HOST: postgres
  #     POSTGRES_PORT: 5432
  #     POSTGRES_DATABASE: embeddings
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   command: node packages/mcp/dist/index-postgres.js

volumes:
  postgres_data:
    driver: local
  ollama_data:
    driver: local

networks:
  default:
    name: claude-context-network